CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    full_name VARCHAR(150) NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Replace the password hash with one generated by PHP password_hash('StrongPassword@123', PASSWORD_DEFAULT).
INSERT INTO admin_users (username, full_name, password_hash)
VALUES ('admin', 'System Administrator', '$2y$10$uWJCF6B8RRN6No1jBjO1xekvR9M4/JL.iGQ7uXf2wKRkM4zjE0T86')
ON DUPLICATE KEY UPDATE username = VALUES(username);
